<?php
declare(strict_types=1);

/**
 * Web installer — runs ONLY when config.php does not exist yet (dispatched from
 * public/index.php). Collects the essentials, generates the pepper + password
 * hash, and writes config.php one level above the document root. Once config.php
 * exists this file is never reached again, so the installer self-locks.
 */

require __DIR__ . '/helpers.php';
require __DIR__ . '/i18n.php';
require __DIR__ . '/csrf.php';

if (session_status() === PHP_SESSION_NONE) {
    session_name('w2b_install');
    session_start();
}
header('X-Robots-Tag: noindex, nofollow');
header('Referrer-Policy: no-referrer');

$cfgFile = dirname(__DIR__) . '/config.php';
$errors = [];
$done = false;
$vals = [
    'base_url'   => rtrim((string) (($_SERVER['HTTPS'] ?? '') && ($_SERVER['HTTPS'] !== 'off') ? 'https' : 'http')
                    . '://' . (string) ($_SERVER['HTTP_HOST'] ?? 'localhost'), '/'),
    'smtp_host'  => '', 'smtp_port' => 587, 'smtp_secure' => 'starttls',
    'smtp_user'  => '', 'smtp_from' => '', 'smtp_from_name' => '', 'dry_run' => true,
];

/** Escape a value for a single-quoted PHP string literal. */
function w2b_php_str(string $v): string
{
    return "'" . addcslashes($v, "\\'") . "'";
}

if (($_SERVER['REQUEST_METHOD'] ?? 'GET') === 'POST') {
    csrf_check();
    $pw  = (string) ($_POST['admin_pw'] ?? '');
    $pw2 = (string) ($_POST['admin_pw2'] ?? '');
    $vals['base_url']       = rtrim(trim((string) ($_POST['base_url'] ?? '')), '/');
    $lang = (string) ($_POST['default_lang'] ?? 'de');
    $lang = isset(available_langs()[$lang]) ? $lang : 'de';
    $vals['smtp_host']      = trim((string) ($_POST['smtp_host'] ?? ''));
    $vals['smtp_port']      = (int) ($_POST['smtp_port'] ?? 587) ?: 587;
    $vals['smtp_secure']    = in_array($_POST['smtp_secure'] ?? 'starttls', ['starttls', 'ssl', ''], true) ? (string) $_POST['smtp_secure'] : 'starttls';
    $vals['smtp_user']      = trim((string) ($_POST['smtp_user'] ?? ''));
    $smtpPass               = (string) ($_POST['smtp_pass'] ?? '');
    $vals['smtp_from']      = trim((string) ($_POST['smtp_from'] ?? ''));
    $vals['smtp_from_name'] = trim((string) ($_POST['smtp_from_name'] ?? ''));
    $vals['dry_run']        = isset($_POST['mail_dry_run']);

    if (strlen($pw) < 8) {
        $errors[] = t('install.err_pw_short');
    }
    if ($pw !== $pw2) {
        $errors[] = t('install.err_pw_match');
    }
    if (!preg_match('#^https?://#i', $vals['base_url'])) {
        $errors[] = t('install.err_base_url');
    }

    if (!$errors) {
        $hash   = password_hash($pw, PASSWORD_DEFAULT);
        $pepper = bin2hex(random_bytes(32));
        $c = "<?php\n// What2Bring configuration — generated by the web installer. Keep private, do not commit.\n"
            . "return [\n"
            . '    ' . w2b_php_str('admin_password_hash') . ' => ' . w2b_php_str($hash) . ",\n"
            . '    ' . w2b_php_str('app_pepper') . ' => ' . w2b_php_str($pepper) . ",\n"
            . '    ' . w2b_php_str('base_url') . ' => ' . w2b_php_str($vals['base_url']) . ",\n"
            . '    ' . w2b_php_str('default_lang') . ' => ' . w2b_php_str($lang) . ",\n"
            . '    ' . w2b_php_str('db_file') . " => __DIR__ . '/data/what2bring.sqlite',\n"
            . '    ' . w2b_php_str('mail_dry_run') . ' => ' . ($vals['dry_run'] ? 'true' : 'false') . ",\n"
            . '    ' . w2b_php_str('smtp') . " => [\n"
            . '        ' . w2b_php_str('host') . ' => ' . w2b_php_str($vals['smtp_host']) . ",\n"
            . '        ' . w2b_php_str('port') . ' => ' . (int) $vals['smtp_port'] . ",\n"
            . '        ' . w2b_php_str('secure') . ' => ' . w2b_php_str($vals['smtp_secure']) . ",\n"
            . '        ' . w2b_php_str('user') . ' => ' . w2b_php_str($vals['smtp_user']) . ",\n"
            . '        ' . w2b_php_str('pass') . ' => ' . w2b_php_str($smtpPass) . ",\n"
            . '        ' . w2b_php_str('from_email') . ' => ' . w2b_php_str($vals['smtp_from']) . ",\n"
            . '        ' . w2b_php_str('from_name') . ' => ' . w2b_php_str($vals['smtp_from_name']) . ",\n"
            . '        ' . w2b_php_str('timeout') . " => 15,\n"
            . '        ' . w2b_php_str('verify_tls') . " => true,\n"
            . "    ],\n];\n";

        if (@file_put_contents($cfgFile, $c) === false) {
            $errors[] = t('install.err_write', ['path' => $cfgFile]);
        } else {
            @chmod($cfgFile, 0640);
            $done = true;
        }
    }
}

$secureOpts = ['starttls' => 'STARTTLS (587)', 'ssl' => 'SSL/TLS (465)', '' => t('install.secure_none')];
?>
<!doctype html>
<html lang="<?= e(current_lang()) ?>">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="robots" content="noindex, nofollow">
    <title><?= e(t('title.install')) ?> · What2Bring</title>
    <link rel="icon" href="data:image/svg+xml,<?= rawurlencode('<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100"><text y=".9em" font-size="90">🧺</text></svg>') ?>">
    <link rel="stylesheet" href="assets/style.css">
</head>
<body class="is-public">
<header class="topbar"><div class="wrap topbar__inner">
    <span class="brand"><span class="brand__mark" aria-hidden="true">🧺</span><span class="brand__name">What2Bring</span></span>
    <span class="lang-switch">
        <?php foreach (available_langs() as $code => $label): ?>
            <?php if ($code === current_lang()): ?><strong><?= e(strtoupper($code)) ?></strong><?php else: ?><a href="?lang=<?= e($code) ?>"><?= e(strtoupper($code)) ?></a><?php endif; ?>
        <?php endforeach; ?>
    </span>
</div></header>

<main class="wrap main">
<?php if ($done): ?>
    <div class="card card--pad-lg center stack">
        <div class="big-emoji" aria-hidden="true">🎉</div>
        <h1><?= e(t('install.done_title')) ?></h1>
        <p class="muted"><?= e(t('install.done_text')) ?></p>
        <p><a class="btn btn--lg" href="index.php?r=admin.login"><?= e(t('install.done_cta')) ?></a></p>
    </div>
<?php else: ?>
    <div style="max-width:640px;margin-inline:auto;">
        <p class="eyebrow"><?= e(t('install.eyebrow')) ?></p>
        <h1><?= e(t('install.title')) ?></h1>
        <p class="muted"><?= e(t('install.intro')) ?></p>

        <?php foreach ($errors as $er): ?>
            <div class="flash flash--error"><?= e($er) ?></div>
        <?php endforeach; ?>

        <form method="post" action="index.php">
            <?= csrf_field() ?>
            <div class="card stack">
                <div class="field">
                    <label for="admin_pw"><?= e(t('install.admin_pw')) ?> *</label>
                    <input type="password" id="admin_pw" name="admin_pw" autocomplete="new-password" required>
                    <p class="hint"><?= e(t('install.admin_pw_hint')) ?></p>
                </div>
                <div class="field">
                    <label for="admin_pw2"><?= e(t('install.admin_pw2')) ?> *</label>
                    <input type="password" id="admin_pw2" name="admin_pw2" autocomplete="new-password" required>
                </div>
                <div class="field">
                    <label for="base_url"><?= e(t('install.base_url')) ?> *</label>
                    <input type="text" id="base_url" name="base_url" value="<?= e($vals['base_url']) ?>" required>
                    <p class="hint"><?= e(t('install.base_url_hint')) ?></p>
                </div>
                <div class="field" style="margin-bottom:0;">
                    <label for="default_lang"><?= e(t('install.lang')) ?></label>
                    <select id="default_lang" name="default_lang">
                        <?php foreach (available_langs() as $code => $label): ?>
                            <option value="<?= e($code) ?>" <?= $code === current_lang() ? 'selected' : '' ?>><?= e($label) ?></option>
                        <?php endforeach; ?>
                    </select>
                </div>
            </div>

            <div class="card stack">
                <h2><?= e(t('install.smtp_title')) ?></h2>
                <p class="hint" style="margin-top:-6px;"><?= e(t('install.smtp_hint')) ?></p>
                <div class="field">
                    <label for="smtp_host"><?= e(t('install.smtp_host')) ?></label>
                    <input type="text" id="smtp_host" name="smtp_host" value="<?= e((string) $vals['smtp_host']) ?>" placeholder="smtp.example.com">
                </div>
                <div class="btn-row" style="gap:14px;">
                    <div class="field" style="flex:1;min-width:120px;margin-bottom:0;">
                        <label for="smtp_port"><?= e(t('install.smtp_port')) ?></label>
                        <input type="number" id="smtp_port" name="smtp_port" value="<?= e((string) $vals['smtp_port']) ?>">
                    </div>
                    <div class="field" style="flex:2;min-width:160px;margin-bottom:0;">
                        <label for="smtp_secure"><?= e(t('install.smtp_secure')) ?></label>
                        <select id="smtp_secure" name="smtp_secure">
                            <?php foreach ($secureOpts as $val => $label): ?>
                                <option value="<?= e($val) ?>" <?= $vals['smtp_secure'] === $val ? 'selected' : '' ?>><?= e($label) ?></option>
                            <?php endforeach; ?>
                        </select>
                    </div>
                </div>
                <div class="field">
                    <label for="smtp_user"><?= e(t('install.smtp_user')) ?></label>
                    <input type="text" id="smtp_user" name="smtp_user" value="<?= e((string) $vals['smtp_user']) ?>" autocomplete="off">
                </div>
                <div class="field">
                    <label for="smtp_pass"><?= e(t('install.smtp_pass')) ?></label>
                    <input type="password" id="smtp_pass" name="smtp_pass" autocomplete="new-password">
                </div>
                <div class="field">
                    <label for="smtp_from"><?= e(t('install.smtp_from')) ?></label>
                    <input type="email" id="smtp_from" name="smtp_from" value="<?= e((string) $vals['smtp_from']) ?>" placeholder="feste@example.com">
                </div>
                <div class="field">
                    <label for="smtp_from_name"><?= e(t('install.smtp_from_name')) ?></label>
                    <input type="text" id="smtp_from_name" name="smtp_from_name" value="<?= e((string) $vals['smtp_from_name']) ?>">
                </div>
                <div class="field" style="margin-bottom:0;">
                    <label style="display:flex;gap:10px;align-items:flex-start;cursor:pointer;font-weight:500;">
                        <input type="checkbox" name="mail_dry_run" value="1" <?= $vals['dry_run'] ? 'checked' : '' ?> style="margin-top:3px;accent-color:var(--accent);width:20px;height:20px;flex:0 0 auto;">
                        <span><?= e(t('install.dry_run')) ?></span>
                    </label>
                </div>
            </div>

            <div class="btn-row">
                <button type="submit" class="btn btn--lg"><?= e(t('install.submit')) ?></button>
            </div>
        </form>
    </div>
<?php endif; ?>
</main>

<footer class="footer"><div class="wrap"><p><?= e(t('footer.tagline')) ?> · <span class="muted"><?= e(t('footer.subtitle')) ?></span></p></div></footer>
</body>
</html>
